sudo: required

services:
  - docker

language: generic

before_install:
  - docker build -t cinguilherme/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cinguilherme/react-test npm test -- --coverage

after_success:
  - docker build -t cinguilherme/multic-client ./client
  - docker build -t cinguilherme/multic-nginx ./nginx
  - docker build -t cinguilherme/multic-server ./server
  - docker build -t cinguilherme/multic-worker ./worker
  
  # push to dockerhub, loging CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USR" --password-stdin
  - docker push cinguilherme/multic-client
  - docker push cinguilherme/multic-nginx
  - docker push cinguilherme/multic-server
  - docker push cinguilherme/multic-worker

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'multic-docker'
  env: 'Multicdocker-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-838492447918'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY